apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "nmapshot.fullname" . }}
  labels:
    {{- include "nmapshot.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "nmapshot.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "nmapshot.labels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "nmapshot.serviceAccountName" . }}
      containers:
        - name: {{ .Chart.Name }}
          image: {{ .Values.image.repository | quote }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          {{- with .Values.env }}
          env:
            {{- range $key, $value := . }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
          {{- end }}
          livenessProbe:
            httpGet:
              path: /docs
              port: http
          readinessProbe:
            httpGet:
              path: /docs
              port: http
